[package]
name = "trijam121"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = "0.8.0-alpha"
structopt = "0.3"
serde = "1"
noise = "0.7"
image = "0.23"